"""Forest plot visualisation for meta‑analysis.

This helper module uses matplotlib to draw a simple forest plot from
effect size data generated by :class:`MetaAnalyzer`.  The plot
displays individual study estimates with confidence intervals and
optionally the pooled estimate.  Users can customise colours and
labels as needed.

"""

from __future__ import annotations

from typing import List, Optional

import matplotlib.pyplot as plt  # type: ignore

from .analyzer import EffectSize


def create_forest_plot(
    effect_sizes: List[EffectSize],
    pooled: Optional[dict] = None,
    title: str = "Forest plot",
    xlabel: str = "Effect size",
    figsize: tuple = (6, 0.5),
    show: bool = False,
) -> plt.Figure:
    """Create a forest plot figure from effect sizes.

    Args:
        effect_sizes: List of individual study effect sizes.
        pooled: Optional pooled result to display as a diamond.  If
            provided, it should contain keys ``effect``, ``ci_lower`` and
            ``ci_upper``.
        title: Plot title.
        xlabel: X‑axis label.
        figsize: Tuple controlling figure size; height will be scaled
            automatically based on the number of studies.
        show: If True, display the plot immediately.

    Returns:
        A matplotlib Figure object.
    """
    n = len(effect_sizes)
    fig_height = max(2.5, n * 0.4)
    fig, ax = plt.subplots(figsize=(figsize[0], fig_height))
    y_positions = list(range(n, 0, -1))
    # Plot each study's CI as a horizontal line
    for i, es in enumerate(effect_sizes):
        y = y_positions[i]
        ax.plot([es.ci_lower, es.ci_upper], [y, y], color="black")
        ax.scatter(es.effect, y, color="black", zorder=3)
        ax.text(
            ax.get_xlim()[0], y, es.study_id, va="center", ha="left",
            fontsize=8
        )
    # Draw pooled effect as a diamond
    if pooled and all(k in pooled for k in ("pooled_effect", "ci_lower", "ci_upper")):
        y = 0.0
        pe = pooled["pooled_effect"]
        ci_l = pooled["ci_lower"]
        ci_u = pooled["ci_upper"]
        # Diamond coordinates
        ax.plot([ci_l, pe], [y - 0.3, y], color="blue")
        ax.plot([pe, ci_u], [y, y - 0.3], color="blue")
        ax.plot([ci_u, pe], [y - 0.3, y - 0.6], color="blue")
        ax.plot([pe, ci_l], [y - 0.6, y - 0.3], color="blue")
        ax.scatter(pe, y - 0.3, color="blue", s=10)
    # Formatting
    ax.set_yticks([])
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    ax.grid(axis="x", linestyle="--", alpha=0.5)
    plt.tight_layout()
    if show:
        plt.show()
    return fig